### ISSUE TITLE
Whats 9+10? 

### ISSUE THREAD

**Issue by JakeyL** [TriCkle-C/TriCkle#2]
^_^ whats 9+10? :joy_cat:

**Comment by valid22** [comment]
This shows How a big lier you are, :laughing: , That's Socket, This is Twisted. STOP TALKING ANNOYINGLY!! You speak as if you wanna Blame Me!!

**Comment by JakeyL** [comment]
No, ITS NOT TWISTED OR SOCKET, ITS 21.

**Comment by valid22** [comment]
21????

**Comment by JakeyL** [comment]
CORRECT! You can close this lulz, or delete it :package:
